<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    exclude-result-prefixes="xs"
    version="2.0">
    <!-- 
        The merged DITA map file may contain cross references to elements from a topic. In this case, the reference looks like:
        
        <xref class="- topic/xref " 
            href="#unique_3/unique_3_Connect_42_my_table_id" 
            ohref="topics/care.dita#care/my_table_id"/>
            
        Where the "ohref" is the original value from the DITA source, and the "href" is generated by the merging process.
        The value of the href cannot be used by the XML+CSS to PDF processor, because it is not a valid IDREF (contains a / )
        so wee need to remove the part before the slash. 
    -->
    <xsl:template match="@href[starts-with( ., '#') and contains(., '/')]">
        <xsl:attribute name="href" select="concat('#',substring-after(., '/'))"/>
    </xsl:template>
    
</xsl:stylesheet>